allowBuilds:
  "@clerk/shared": true
  esbuild: true
  sharp: true
  unrs-resolver: true
  "@libsql/client": true

minimumReleaseAgeExclude:
  - '@ai-sdk/openai@3.0.74'
  - '@clerk/backend@3.8.3'
  - '@clerk/nextjs@7.5.8'
  - '@clerk/react@6.11.0'
  - '@clerk/shared@4.21.0'

overrides:
  postcss: ">=8.5.10"
  esbuild: ">=0.25.0"
  "@ai-sdk/provider-utils": ">=3.0.98"
