#!/usr/bin/env bash
# Clerk Development キーの正本は Clerk CLI（linked app / INSTANCE=dev）。
# このスクリプトは毎回 CLI から取り直し、全ターゲットへ冪等に上書きする。
# 古い .env.local / 手元ファイルを正本にしてはいけない（環境間ドリフトの元）。
#
# 同期先:
#   1) GitHub Actions Secrets（E2E）
#   2) $SECRETS_DIR/.env.clerk（Cloud Agent / ローカル共有置き場）
#   3) リポの .env.local（clerk env pull の merge。任意で SKIP_DOTENV_LOCAL=1）
#
# 使い方（番人マシン・リポ root）:
#   clerk auth login && clerk link   # 初回のみ
#   ./scripts/sync-clerk-dev-secrets.sh
set -euo pipefail

REPO="${REPO:-sinoda1114/gmail-kanban}"
INSTANCE="${INSTANCE:-dev}"
SECRETS_DIR="${SECRETS_DIR:-$HOME/.config/gmail-kanban-secrets}"
SKIP_GITHUB="${SKIP_GITHUB:-0}"
SKIP_SECRETS_DIR="${SKIP_SECRETS_DIR:-0}"
SKIP_DOTENV_LOCAL="${SKIP_DOTENV_LOCAL:-0}"
ROOT="$(cd "$(dirname "$0")/.." && pwd)"

fingerprint() {
  # 値は出さず、比較用の短いハッシュだけ返す
  printf '%s\n%s\n' "$1" "$2" | shasum -a 256 | awk '{print substr($1,1,16)}'
}

read_env_key() {
  local file="$1" key="$2" line raw
  [[ -f "$file" ]] || return 0
  line="$(grep -E "^[[:space:]]*${key}=" "$file" | tail -n 1 || true)"
  [[ -n "$line" ]] || return 0
  raw="${line#*=}"
  raw="${raw#"${raw%%[![:space:]]*}"}"
  raw="${raw%"${raw##*[![:space:]]}"}"
  if [[ "${#raw}" -ge 2 ]]; then
    if [[ "${raw:0:1}" == '"' && "${raw: -1}" == '"' ]]; then
      raw="${raw:1:${#raw}-2}"
    elif [[ "${raw:0:1}" == "'" && "${raw: -1}" == "'" ]]; then
      raw="${raw:1:${#raw}-2}"
    fi
  fi
  printf '%s' "$raw"
}

write_env_clerk() {
  local dest="$1" pk="$2" sk="$3"
  umask 077
  mkdir -p "$(dirname "$dest")"
  cat >"$dest" <<EOF
# Generated by scripts/sync-clerk-dev-secrets.sh — do not hand-edit.
# Source of truth: clerk env pull --instance ${INSTANCE}
NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${pk}
CLERK_SECRET_KEY=${sk}
EOF
  chmod 600 "$dest"
}

require_cmd() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "$1 がありません。" >&2
    exit 1
  fi
}

require_cmd curl
require_cmd shasum
if ! command -v clerk >/dev/null 2>&1; then
  echo "clerk CLI がありません。npm i -g clerk のあと clerk auth login && clerk link" >&2
  exit 1
fi
if [[ "$SKIP_GITHUB" != "1" ]]; then
  require_cmd gh
fi

TMP="$(mktemp -t clerk-dev-sync.XXXXXX)"
trap 'rm -f "$TMP"' EXIT

echo "==> Pulling Clerk keys (instance=${INSTANCE}) — this is the only source of truth"
# 壊れたローカル env を正本にしない
env -u CLERK_SECRET_KEY -u NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY \
  clerk env pull --instance "$INSTANCE" --file "$TMP" --mode agent

PK="$(read_env_key "$TMP" NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY)"
SK="$(read_env_key "$TMP" CLERK_SECRET_KEY)"

if [[ -z "$PK" || -z "$SK" ]]; then
  echo "clerk env pull の結果にキーがありません。clerk auth login && clerk link を確認してください。" >&2
  exit 1
fi
case "$PK" in pk_test_*) ;; *)
  echo "Development キーが必要です（PK 先頭: ${PK:0:8}）。INSTANCE=dev で実行してください。" >&2
  exit 1
  ;;
esac
case "$SK" in sk_test_*) ;; *)
  echo "Development キーが必要です（SK 先頭: ${SK:0:8}）。INSTANCE=dev で実行してください。" >&2
  exit 1
  ;;
esac

FP="$(fingerprint "$PK" "$SK")"
echo "Fingerprint: ${FP} (PK=${PK:0:8}… len=${#PK}, SK=${SK:0:8}… len=${#SK})"

echo "==> Checking Testing Token API"
HTTP_CODE="$(
  curl -sS -o /dev/null -w '%{http_code}' \
    -X POST 'https://api.clerk.com/v1/testing_tokens' \
    -H "Authorization: Bearer ${SK}" \
    -H 'Content-Type: application/json'
)"
if [[ "$HTTP_CODE" != "200" ]]; then
  echo "Testing Token API が ${HTTP_CODE}。リンク先アプリ / キーを確認してください。" >&2
  exit 1
fi
echo "Testing Token API: OK"

CHANGED=0

# --- 1) secrets dir (.env.clerk) ---
if [[ "$SKIP_SECRETS_DIR" != "1" ]]; then
  DEST="${SECRETS_DIR}/.env.clerk"
  FP_FILE="${SECRETS_DIR}/.clerk-dev.fingerprint"
  OLD_FP=""
  [[ -f "$FP_FILE" ]] && OLD_FP="$(tr -d '[:space:]' <"$FP_FILE" || true)"
  OLD_PK="$(read_env_key "$DEST" NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY)"
  OLD_SK="$(read_env_key "$DEST" CLERK_SECRET_KEY)"
  if [[ -n "$OLD_PK" && -n "$OLD_SK" ]]; then
    COMPUTED_OLD="$(fingerprint "$OLD_PK" "$OLD_SK")"
  else
    COMPUTED_OLD=""
  fi
  if [[ "$COMPUTED_OLD" == "$FP" && "$OLD_FP" == "$FP" ]]; then
    echo "secrets dir: unchanged (${DEST})"
  else
    write_env_clerk "$DEST" "$PK" "$SK"
    printf '%s\n' "$FP" >"$FP_FILE"
    chmod 600 "$FP_FILE"
    echo "secrets dir: updated (${DEST})"
    CHANGED=1
  fi
fi

# --- 2) repo .env.local via clerk (merge) ---
if [[ "$SKIP_DOTENV_LOCAL" != "1" ]]; then
  LOCAL_ENV="${ROOT}/.env.local"
  OLD_PK="$(read_env_key "$LOCAL_ENV" NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY)"
  OLD_SK="$(read_env_key "$LOCAL_ENV" CLERK_SECRET_KEY)"
  if [[ -n "$OLD_PK" && -n "$OLD_SK" && "$(fingerprint "$OLD_PK" "$OLD_SK")" == "$FP" ]]; then
    echo ".env.local: unchanged"
  else
    (
      cd "$ROOT"
      env -u CLERK_SECRET_KEY -u NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY \
        clerk env pull --instance "$INSTANCE" --file .env.local --mode agent
    )
    NEW_PK="$(read_env_key "$LOCAL_ENV" NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY)"
    NEW_SK="$(read_env_key "$LOCAL_ENV" CLERK_SECRET_KEY)"
    if [[ "$(fingerprint "$NEW_PK" "$NEW_SK")" != "$FP" ]]; then
      echo ".env.local: pull 後も fingerprint が一致しません" >&2
      exit 1
    fi
    echo ".env.local: updated"
    CHANGED=1
  fi
fi

# --- 3) GitHub Actions（読めないので毎回 set = 冪等上書き） ---
if [[ "$SKIP_GITHUB" != "1" ]]; then
  echo "GitHub Actions secrets: setting (always overwrite; values not readable back)"
  printf '%s' "$PK" | gh secret set NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY -R "$REPO"
  printf '%s' "$SK" | gh secret set CLERK_SECRET_KEY -R "$REPO"
  # リポ側に「いつ同期したか」だけ残す（値は残さない）
  META="${SECRETS_DIR}/.clerk-dev.github-synced"
  mkdir -p "$SECRETS_DIR"
  umask 077
  {
    echo "fingerprint=${FP}"
    echo "repo=${REPO}"
    echo "synced_at=$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  } >"$META"
  chmod 600 "$META"
  echo "GitHub Actions secrets: synced (fingerprint=${FP})"
  CHANGED=1
fi

echo "==> Done (fingerprint=${FP})"
if [[ "$CHANGED" -eq 0 ]]; then
  echo "All local targets already matched Clerk. GitHub was skipped or unchanged path."
fi
echo "Rule: never treat a stale .env file as source of truth. Re-run this script after any Clerk key rotation."
