#!/usr/bin/env bash
# Clerk Development キーの正本は Clerk CLI（INSTANCE=dev）。
# 毎回 CLI から取り直し、全ターゲットへ冪等に上書きする。
# 古い .env.local を正本にしてはいけない。
#
# 同期先:
#   1) GitHub Actions Secrets（E2E）
#   2) $SECRETS_DIR/.env.clerk
#   3) リポの .env.local（SKIP_DOTENV_LOCAL=1 で省略可）
#
# 前提: clerk auth login（link は不要。アプリは CLERK_APP / scripts/clerk-app.id）
# 使い方:
#   cd ~/dev/gmail-kanban && ./scripts/sync-clerk-dev-secrets.sh
set -euo pipefail

REPO="${REPO:-sinoda1114/gmail-kanban}"
INSTANCE="${INSTANCE:-dev}"
SECRETS_DIR="${SECRETS_DIR:-$HOME/.config/gmail-kanban-secrets}"
SKIP_GITHUB="${SKIP_GITHUB:-0}"
SKIP_SECRETS_DIR="${SKIP_SECRETS_DIR:-0}"
SKIP_DOTENV_LOCAL="${SKIP_DOTENV_LOCAL:-0}"
EXPECTED_PKG_NAME="${EXPECTED_PKG_NAME:-gmail-kanban}"

SCRIPT_PATH="$(cd "$(dirname "$0")" && pwd)/$(basename "$0")"
SCRIPT_DIR="$(cd "$(dirname "$SCRIPT_PATH")" && pwd)"

# 公開の Application ID（秘密ではない）。CLERK_APP で上書き可。
# リポ内の scripts/clerk-app.id があればそれを優先。
resolve_clerk_app() {
  if [[ -n "${CLERK_APP:-}" ]]; then
    printf '%s\n' "$CLERK_APP"
    return
  fi
  if [[ -f "${SCRIPT_DIR}/clerk-app.id" ]]; then
    tr -d '[:space:]' <"${SCRIPT_DIR}/clerk-app.id"
    return
  fi
  # /tmp 実行用フォールバック（Clerk Application ID はシークレットではない）
  printf '%s\n' "app_3HcCjWlFNG5hXBCkT7Xmv9Mp77Y"
}

is_gmail_kanban_root() {
  local root="$1" name remote
  [[ -f "${root}/package.json" ]] || return 1
  name="$(
    node -e 'const p=require(process.argv[1]); process.stdout.write(String(p.name||""))' \
      "${root}/package.json" 2>/dev/null || true
  )"
  [[ "$name" == "$EXPECTED_PKG_NAME" ]] || return 1
  if remote="$(git -C "$root" remote get-url origin 2>/dev/null || true)" && [[ -n "$remote" ]]; then
    case "$remote" in
      *gmail-kanban*) return 0 ;;
      *) return 1 ;;
    esac
  fi
  return 0
}

resolve_root() {
  local candidate
  if [[ -f "${SCRIPT_DIR}/../package.json" && -d "${SCRIPT_DIR}/../scripts" ]]; then
    candidate="$(cd "${SCRIPT_DIR}/.." && pwd)"
    if is_gmail_kanban_root "$candidate"; then
      printf '%s\n' "$candidate"
      return
    fi
  fi
  if candidate="$(git -C "$PWD" rev-parse --show-toplevel 2>/dev/null)"; then
    if is_gmail_kanban_root "$candidate"; then
      printf '%s\n' "$candidate"
      return
    fi
  fi
  if is_gmail_kanban_root "$PWD"; then
    printf '%s\n' "$PWD"
    return
  fi
  echo "gmail-kanban のリポ root を特定できません（package.json name=${EXPECTED_PKG_NAME}）。" >&2
  echo "cd ~/dev/gmail-kanban してから実行するか、SKIP_DOTENV_LOCAL=1 で .env.local 更新を省略してください。" >&2
  exit 1
}

sha256_16() {
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum | awk '{print substr($1,1,16)}'
  elif command -v shasum >/dev/null 2>&1; then
    shasum -a 256 | awk '{print substr($1,1,16)}'
  else
    echo "sha256sum または shasum が必要です。" >&2
    exit 1
  fi
}

fingerprint() {
  printf '%s\n%s\n' "$1" "$2" | sha256_16
}

read_env_key() {
  local file="$1" key="$2" line raw
  [[ -f "$file" ]] || return 0
  line="$(grep -E "^[[:space:]]*${key}=" "$file" | tail -n 1 || true)"
  [[ -n "$line" ]] || return 0
  raw="${line#*=}"
  raw="${raw#"${raw%%[![:space:]]*}"}"
  raw="${raw%"${raw##*[![:space:]]}"}"
  if [[ "${#raw}" -ge 2 ]]; then
    if [[ "${raw:0:1}" == '"' && "${raw: -1}" == '"' ]]; then
      raw="${raw:1:${#raw}-2}"
    elif [[ "${raw:0:1}" == "'" && "${raw: -1}" == "'" ]]; then
      raw="${raw:1:${#raw}-2}"
    fi
  fi
  printf '%s' "$raw"
}

write_env_clerk() {
  local dest="$1" pk="$2" sk="$3"
  umask 077
  mkdir -p "$(dirname "$dest")"
  cat >"$dest" <<EOF
# Generated by scripts/sync-clerk-dev-secrets.sh — do not hand-edit.
# Source of truth: clerk env pull --instance ${INSTANCE}
NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${pk}
CLERK_SECRET_KEY=${sk}
EOF
  chmod 600 "$dest"
}

upsert_env_keys() {
  local file="$1" pk="$2" sk="$3" tmp status
  umask 077
  tmp="$(mktemp "${file}.XXXXXX")"
  # RETURN で関数抜け時に掃除（mv 成功後は消えている想定）
  # shellcheck disable=SC2064
  trap "rm -f '$tmp'" RETURN
  if [[ -f "$file" ]]; then
    set +e
    grep -Ev '^[[:space:]]*(NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY|CLERK_SECRET_KEY)=' "$file" >"$tmp"
    status=$?
    set -e
    if [[ "$status" -gt 1 ]]; then
      echo "${file} の読み取りに失敗しました（grep exit=${status}）。中断します。" >&2
      exit 1
    fi
  else
    : >"$tmp"
  fi
  {
    printf 'NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=%s\n' "$pk"
    printf 'CLERK_SECRET_KEY=%s\n' "$sk"
  } >>"$tmp"
  mv "$tmp" "$file"
  chmod 600 "$file"
  trap - RETURN
}

require_cmd() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "$1 がありません。" >&2
    exit 1
  fi
}

require_cmd curl
if ! command -v sha256sum >/dev/null 2>&1 && ! command -v shasum >/dev/null 2>&1; then
  echo "sha256sum または shasum が必要です。" >&2
  exit 1
fi
if ! command -v clerk >/dev/null 2>&1; then
  echo "clerk CLI がありません。npm i -g clerk のあと clerk auth login" >&2
  exit 1
fi
if [[ "$SKIP_GITHUB" != "1" ]]; then
  require_cmd gh
fi

CLERK_APP="$(resolve_clerk_app)"
ROOT=""
if [[ "$SKIP_DOTENV_LOCAL" != "1" ]]; then
  ROOT="$(resolve_root)"
fi

TMP="$(mktemp -t clerk-dev-sync.XXXXXX)"
trap 'rm -f "$TMP"' EXIT

echo "==> Pulling Clerk keys (instance=${INSTANCE}, app=${CLERK_APP}) — this is the only source of truth"
if [[ -n "$ROOT" ]]; then
  echo "Repo root: ${ROOT}"
fi
env -u CLERK_SECRET_KEY -u NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY \
  clerk env pull --app "$CLERK_APP" --instance "$INSTANCE" --file "$TMP" --mode agent

PK="$(read_env_key "$TMP" NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY)"
SK="$(read_env_key "$TMP" CLERK_SECRET_KEY)"

if [[ -z "$PK" || -z "$SK" ]]; then
  echo "clerk env pull の結果にキーがありません。clerk auth login を確認してください。" >&2
  exit 1
fi
case "$PK" in pk_test_*) ;; *)
  echo "Development キーが必要です（PK 先頭: ${PK:0:8}）。INSTANCE=dev で実行してください。" >&2
  exit 1
  ;;
esac
case "$SK" in sk_test_*) ;; *)
  echo "Development キーが必要です（SK 先頭: ${SK:0:8}）。INSTANCE=dev で実行してください。" >&2
  exit 1
  ;;
esac

FP="$(fingerprint "$PK" "$SK")"
echo "Fingerprint: ${FP} (PK=${PK:0:8}… len=${#PK}, SK=${SK:0:8}… len=${#SK})"

echo "==> Checking Testing Token API"
HTTP_CODE="$(
  curl -sS -o /dev/null -w '%{http_code}' \
    -X POST 'https://api.clerk.com/v1/testing_tokens' \
    -H "Authorization: Bearer ${SK}" \
    -H 'Content-Type: application/json'
)"
if [[ "$HTTP_CODE" != "200" ]]; then
  echo "Testing Token API が ${HTTP_CODE}。アプリ / キーを確認してください。" >&2
  exit 1
fi
echo "Testing Token API: OK"

CHANGED=0

if [[ "$SKIP_SECRETS_DIR" != "1" ]]; then
  DEST="${SECRETS_DIR}/.env.clerk"
  FP_FILE="${SECRETS_DIR}/.clerk-dev.fingerprint"
  OLD_FP=""
  [[ -f "$FP_FILE" ]] && OLD_FP="$(tr -d '[:space:]' <"$FP_FILE" || true)"
  OLD_PK="$(read_env_key "$DEST" NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY)"
  OLD_SK="$(read_env_key "$DEST" CLERK_SECRET_KEY)"
  if [[ -n "$OLD_PK" && -n "$OLD_SK" ]]; then
    COMPUTED_OLD="$(fingerprint "$OLD_PK" "$OLD_SK")"
  else
    COMPUTED_OLD=""
  fi
  if [[ "$COMPUTED_OLD" == "$FP" && "$OLD_FP" == "$FP" ]]; then
    echo "secrets dir: unchanged (${DEST})"
  else
    write_env_clerk "$DEST" "$PK" "$SK"
    printf '%s\n' "$FP" >"$FP_FILE"
    chmod 600 "$FP_FILE"
    echo "secrets dir: updated (${DEST})"
    CHANGED=1
  fi
fi

if [[ "$SKIP_DOTENV_LOCAL" != "1" ]]; then
  LOCAL_ENV="${ROOT}/.env.local"
  OLD_PK="$(read_env_key "$LOCAL_ENV" NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY)"
  OLD_SK="$(read_env_key "$LOCAL_ENV" CLERK_SECRET_KEY)"
  if [[ -n "$OLD_PK" && -n "$OLD_SK" && "$(fingerprint "$OLD_PK" "$OLD_SK")" == "$FP" ]]; then
    echo ".env.local: unchanged (${LOCAL_ENV})"
  else
    upsert_env_keys "$LOCAL_ENV" "$PK" "$SK"
    echo ".env.local: updated (${LOCAL_ENV})"
    CHANGED=1
  fi
fi

if [[ "$SKIP_GITHUB" != "1" ]]; then
  echo "GitHub Actions secrets: setting (always overwrite; values not readable back)"
  printf '%s' "$PK" | gh secret set NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY -R "$REPO"
  printf '%s' "$SK" | gh secret set CLERK_SECRET_KEY -R "$REPO"
  META="${SECRETS_DIR}/.clerk-dev.github-synced"
  mkdir -p "$SECRETS_DIR"
  umask 077
  {
    echo "fingerprint=${FP}"
    echo "repo=${REPO}"
    echo "synced_at=$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  } >"$META"
  chmod 600 "$META"
  echo "GitHub Actions secrets: synced (fingerprint=${FP})"
  CHANGED=1
fi

echo "==> Done (fingerprint=${FP})"
echo "Targets: secrets_dir=$([ "$SKIP_SECRETS_DIR" = "1" ] && echo skip || echo on) dotenv_local=$([ "$SKIP_DOTENV_LOCAL" = "1" ] && echo skip || echo on) github=$([ "$SKIP_GITHUB" = "1" ] && echo skip || echo on) local_writes_changed=${CHANGED}"
echo "Rule: never treat a stale .env file as source of truth. Re-run this script after any Clerk key rotation."
